# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

# From https://github.com/healyke/SIDER/blob/master/.travis.yml
before_install:
  - sudo add-apt-repository ppa:marutter/rrutter -y
  - sudo apt-get update
  - sudo apt-get install jags
#  - sudo apt-get install r-cran-rjags
  
r_packages:
  - rjags
  - rstan
